#!/bin/bash

DPNS_COMPOSES=()
. ${0%run}load

if [ "${#DPNS_COMPOSES[*]}" = "0" ]; then
  echo "Empty compose list."
  exit 0
fi

for cf in $DPNS_COMPOSES; do
    if [ -e "$cf/docker-compose.yml" ]; then
	cf="$cf/docker-compose.yml"
    fi

    docker-compose up -d -f "$cf"
done
