#!/bin/bash

DPNS_COMPOSES=()
. ${0%run}load

if [ "${#DPNS_COMPOSES[*]}" = "0" ]; then
  echo "Empty compose list."
  exit 0
fi

for dn in $DPNS_COMPOSES; do
    if [ -d "$dn" ]; then
        cd "$dn" && docker-compose up -d
    else
        cf=$(basename $dn)
        dn=$(dirname $dn)
        cd "$dn" && docker-compose -f "$cf" up -d
    fi
done
